apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-ui.my-apps.tap.20240507000532.0.0+build.6aff574
spec:
  refName: where-for-dinner-ui.my-apps.tap
  version: 20240507000532.0.0+build.6aff574
  releaseNotes: |
    Release v20240507000532.0.0+build.6aff574 of package where-for-dinner-ui.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tap-ci/ci-pipeline/apps-06-05-2024-17-53-35-810877072/where-for-dinner-ui-my-apps-bundle@sha256:d2df7b3ae8d76265320990f2d3aed71b97184ab70015fe0c82e67d629cd5d777
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

